# Generated by Django 4.2 on 2023-05-16 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_discount_order_latitude_order_longtitude_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='Delivery Fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price'),
        ),
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('card_number', models.CharField(max_length=255, verbose_name='Card Number')),
                ('expire_date', models.DateField(verbose_name='Expire Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'My Card',
                'verbose_name_plural': 'My Cards',
            },
        ),
    ]
